#!/bin/bash

cp aceattac.rom /media/$USER/POCKET/Assets/jts16b/common
cp afighere.rom /media/$USER/POCKET/Assets/jts16b/common
cp afigherf.rom /media/$USER/POCKET/Assets/jts16b/common
cp afigherg.rom /media/$USER/POCKET/Assets/jts16b/common
cp afigherh.rom /media/$USER/POCKET/Assets/jts16b/common
cp aliensyn.rom /media/$USER/POCKET/Assets/jts16b/common
cp alienyn3.rom /media/$USER/POCKET/Assets/jts16b/common
cp alienyn7.rom /media/$USER/POCKET/Assets/jts16b/common
cp alienynj.rom /media/$USER/POCKET/Assets/jts16b/common
cp altbeast.rom /media/$USER/POCKET/Assets/jts16b/common
cp altbest2.rom /media/$USER/POCKET/Assets/jts16b/common
cp altbest4.rom /media/$USER/POCKET/Assets/jts16b/common
cp altbest5.rom /media/$USER/POCKET/Assets/jts16b/common
cp altbest6.rom /media/$USER/POCKET/Assets/jts16b/common
cp altbestj.rom /media/$USER/POCKET/Assets/jts16b/common
cp altbetj1.rom /media/$USER/POCKET/Assets/jts16b/common
cp altbetj3.rom /media/$USER/POCKET/Assets/jts16b/common
cp atomicp.rom /media/$USER/POCKET/Assets/jts16b/common
cp aurail.rom /media/$USER/POCKET/Assets/jts16b/common
cp aurail1.rom /media/$USER/POCKET/Assets/jts16b/common
cp aurailj.rom /media/$USER/POCKET/Assets/jts16b/common
cp bayroute.rom /media/$USER/POCKET/Assets/jts16b/common
cp bayrote1.rom /media/$USER/POCKET/Assets/jts16b/common
cp bayrotej.rom /media/$USER/POCKET/Assets/jts16b/common
cp bullet.rom /media/$USER/POCKET/Assets/jts16b/common
cp cencourt.rom /media/$USER/POCKET/Assets/jts16b/common
cp cotton.rom /media/$USER/POCKET/Assets/jts16b/common
cp cottonj.rom /media/$USER/POCKET/Assets/jts16b/common
cp cottonja.rom /media/$USER/POCKET/Assets/jts16b/common
cp cottonu.rom /media/$USER/POCKET/Assets/jts16b/common
cp ddux.rom /media/$USER/POCKET/Assets/jts16b/common
cp ddux1.rom /media/$USER/POCKET/Assets/jts16b/common
cp dduxj.rom /media/$USER/POCKET/Assets/jts16b/common
cp defense.rom /media/$USER/POCKET/Assets/jts16b/common
cp dfjail.rom /media/$USER/POCKET/Assets/jts16b/common
cp dunkshot.rom /media/$USER/POCKET/Assets/jts16b/common
cp dunksota.rom /media/$USER/POCKET/Assets/jts16b/common
cp dunksoto.rom /media/$USER/POCKET/Assets/jts16b/common
cp eswat.rom /media/$USER/POCKET/Assets/jts16b/common
cp eswatj.rom /media/$USER/POCKET/Assets/jts16b/common
cp eswatj1.rom /media/$USER/POCKET/Assets/jts16b/common
cp eswatu.rom /media/$USER/POCKET/Assets/jts16b/common
cp exctleag.rom /media/$USER/POCKET/Assets/jts16b/common
cp fantzn2x.rom /media/$USER/POCKET/Assets/jts16b/common
cp fantz2xp.rom /media/$USER/POCKET/Assets/jts16b/common
cp fpoint.rom /media/$USER/POCKET/Assets/jts16b/common
cp fpoint1.rom /media/$USER/POCKET/Assets/jts16b/common
cp goldnaxe.rom /media/$USER/POCKET/Assets/jts16b/common
cp goldnxe1.rom /media/$USER/POCKET/Assets/jts16b/common
cp goldnxe2.rom /media/$USER/POCKET/Assets/jts16b/common
cp goldnxe3.rom /media/$USER/POCKET/Assets/jts16b/common
cp goldnxej.rom /media/$USER/POCKET/Assets/jts16b/common
cp goldnxeu.rom /media/$USER/POCKET/Assets/jts16b/common
cp hwchamp.rom /media/$USER/POCKET/Assets/jts16b/common
cp hwchampa.rom /media/$USER/POCKET/Assets/jts16b/common
cp hwchampj.rom /media/$USER/POCKET/Assets/jts16b/common
cp isgsm.rom /media/$USER/POCKET/Assets/jts16b/common
cp mvp.rom /media/$USER/POCKET/Assets/jts16b/common
cp mvpj.rom /media/$USER/POCKET/Assets/jts16b/common
cp passsht.rom /media/$USER/POCKET/Assets/jts16b/common
cp passshta.rom /media/$USER/POCKET/Assets/jts16b/common
cp passshtj.rom /media/$USER/POCKET/Assets/jts16b/common
cp riotcity.rom /media/$USER/POCKET/Assets/jts16b/common
cp ryukyu.rom /media/$USER/POCKET/Assets/jts16b/common
cp ryukyua.rom /media/$USER/POCKET/Assets/jts16b/common
cp sdib.rom /media/$USER/POCKET/Assets/jts16b/common
cp shinobi2.rom /media/$USER/POCKET/Assets/jts16b/common
cp shinobi3.rom /media/$USER/POCKET/Assets/jts16b/common
cp shinobi4.rom /media/$USER/POCKET/Assets/jts16b/common
cp shinobi5.rom /media/$USER/POCKET/Assets/jts16b/common
cp shinobi6.rom /media/$USER/POCKET/Assets/jts16b/common
cp sjryuko.rom /media/$USER/POCKET/Assets/jts16b/common
cp snapper.rom /media/$USER/POCKET/Assets/jts16b/common
cp sonicbom.rom /media/$USER/POCKET/Assets/jts16b/common
cp suprleag.rom /media/$USER/POCKET/Assets/jts16b/common
cp tetris1.rom /media/$USER/POCKET/Assets/jts16b/common
cp tetris2.rom /media/$USER/POCKET/Assets/jts16b/common
cp timescan.rom /media/$USER/POCKET/Assets/jts16b/common
cp toryumon.rom /media/$USER/POCKET/Assets/jts16b/common
cp tturf.rom /media/$USER/POCKET/Assets/jts16b/common
cp tturfu.rom /media/$USER/POCKET/Assets/jts16b/common
cp ultracin.rom /media/$USER/POCKET/Assets/jts16b/common
cp wb3.rom /media/$USER/POCKET/Assets/jts16b/common
cp wb32.rom /media/$USER/POCKET/Assets/jts16b/common
cp wb33.rom /media/$USER/POCKET/Assets/jts16b/common
cp wb34.rom /media/$USER/POCKET/Assets/jts16b/common
cp wrestwar.rom /media/$USER/POCKET/Assets/jts16b/common
cp wrestar1.rom /media/$USER/POCKET/Assets/jts16b/common
cp wrestar2.rom /media/$USER/POCKET/Assets/jts16b/common
