#!/bin/bash

GAME=shinobi
SCENE=
OTHER=
HEXDUMP=-nohex
SIMULATOR=-verilator
SDRAM_SNAP=

while [ $# -gt 0 ]; do
    case $1 in
    	-s)
            shift
    		SCENE=$1;;
    	*)
            OTHER="$OTHER $1";;
    esac
    shift
done

if [ ! -z "$SCENE" ]; then
	echo "Simulating scene $SCENE"

	if [ ! -e $GAME/char$SCENE.bin ]; then
	    echo Cannot open scene files
	    exit 1
	fi

	drop1    < $GAME/char${SCENE}.bin > char_hi.bin
	drop1 -l < $GAME/char${SCENE}.bin > char_lo.bin

	drop1    < $GAME/pal${SCENE}.bin > pal_hi.bin
	drop1 -l < $GAME/pal${SCENE}.bin > pal_lo.bin

	drop1    < $GAME/obj${SCENE}.bin > obj_hi.bin
	drop1 -l < $GAME/obj${SCENE}.bin > obj_lo.bin

    hexdump -v -e '/1 "%02X "' -s 0xe00 shinobi/char${SCENE}.bin > mmr.hex

	cp $GAME/scr${SCENE}.bin scr.bin
    OTHER="$OTHER -d NOMAIN -video -time 40"
    SDRAM_SNAP="-snap scr.bin 0 0x200000"
else
    rm -f char_*.bin pal_*.bin obj_*.bin scr.bin
fi

if which ncverilog >/dev/null; then
    SIMULATOR=
    HEXDUMP=
fi

jtsim_sdram $HEXDUMP -header 32 sndcpu pcmdata gfx1 obj pcmfirm \
    -region maincpu 0 0 \
    -region sndcpu  1 0 \
    -region gfx1    2 0 \
    -region obj     3 0 \
    $SDRAM_SNAP || exit $?

jtsim -mist -sysname s16 $SIMULATOR \
	-videow 320 -videoh 224 \
    -def ../../hdl/jts16.def -d JTFRAME_SIM_ROMRQ_NOCHECK $OTHER || exit $?

if [[ ! -z "$SCENE" && -e frame_1.jpg ]]; then
	eom frame_1.jpg 2> /dev/null
fi