
name: s16 for neptuno

on:
  push:
    branches:
      - build
      - neptuno
      - build_s16

  workflow_dispatch:

  repository_dispatch:
    types: rebuild

jobs:

  neptuno_compilation:

    env:
      FTPUSER: ${{ secrets.FTPUSER }}
      FTPPASS: ${{ secrets.FTPPASS }}

    runs-on: ubuntu-latest

    container:
      image: jotego/jtcore13
      credentials:
        username: jotego
        password: ${{ secrets.DOCKER_LOGIN }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: check out
        uses: actions/checkout@v3
        with:
          submodules: true
          repository: ${{ github.repository }}
          token: ${{ secrets.TOKEN }}
      - name: Get YAML package
        run: go get gopkg.in/yaml.v2
      - name: compile for neptuno
        run: /docked_build.sh s16 -neptuno  
